[package]
name = "deo"
version = "0.0.1"
authors = []

[addresses]
deo = "_"
meridian = "_"
echelon = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
