[package]
name = "deo"
version = "0.0.1"
authors = []

[addresses]
movement_framework = "0x1"
deo = "_"
meridian = "_"
echelon = "_"

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }
